print("##"*100)
texto="Olá mundo"
tamanho=len(texto)
texto=texto.upper()
print(texto)
texto=texto.lower()
print(texto)
texto=texto.capitalize()
print(texto)
texto=texto.strip()
print(texto)
texto=texto.replace(" ","-")
print(texto)
print(texto.isdigit())
frase="Olá mundo, ocomputador é uma torradeira"
palavras=frase.split(" ")
print(palavras, "split")
print(len(palavras))
print(palavras[1])
posição=frase.index("m")
print(posição)
posição=frase.find("m")
if posição==-1:
    print("não encontrei")
else:
    print("encontrei na posição"+str(posição))
coidigo=ord("a")
print(coidigo)
lrtra=chr(coidigo)
print(lrtra)